### ISSUE TITLE
Changes to make which have fallen out of rust-zarr

### ISSUE THREAD

**Issue by clbarnes** [aschampion/rust-n5#36]
- Factor N5Lister from N5Reader
- All Reader traits should return Results

**Comment by aschampion** [comment]
Filesystem's `set_attributes` has a check `if new != existing` which seems it should be `if merged != existing`.

**Comment by aschampion** [comment]
Closed by:

- eec0dff246aa0c6d3c967098945d2f3b16f9baeb
- 9039bd8cd9235d0f786ff7ad52507876ca5e0d21
- 5249e2f48800d9f7998903cb696d81652def2d3d
